Add Algolia Search
Devolutions/doc pull request #161
Opened 2023-02-27 20:51 UTC by michael-proulx

2023-02-27 21:40 UTC, forestmaxime requested changes

2023-02-27 21:40 UTC, forestmaxime commented on docs/_includes/scripts/search.js
> +      // {
commented code

2023-02-27 21:40 UTC, forestmaxime commented on utils/algolia.js
> +        for (;;) {
as-tu une autre manière de faire ça, ça semble risqué une loop infini!

2023-02-27 22:01 UTC, michael-proulx commented on utils/algolia.js
> +        for (;;) {
J'ai pas trouvé d'autre façon de faire exec mon regex plusieurs fois sur le même résultat sans cette loop.

Il break aussitôt qu'il a plus de headingContentMatch à ligne 55

2023-02-27 22:16 UTC, forestmaxime commented on docs/_includes/scripts/search.js
> +      // {
C'est bon alors pour ceci

2023-02-27 22:20 UTC, forestmaxime requested changes

2023-02-27 22:20 UTC, forestmaxime commented on utils/algolia.js
> +        for (;;) {
Je crois avoir une idée, de ma compréhension du code l'objectif c'est de split le content par \r ou \n.

Tu peux passer ta Regex à ta string et avoir un array que tu peux boucler dessus. Ça serait une solution potentielle si ma compréhension est bonne.

Ex:
'ma super string'.split(regex)

2023-02-28 13:15 UTC, michael-proulx commented on utils/algolia.js
> +        for (;;) {
Le regex utiliser ne split pas le \r ou \n, mais va match toute les h1,h2,h3 et paragraphe, le exec dans le for(;;) me permet de get chaque match de la string et de fill mon array avec chacune d'elle.

Je pourrais réessayer le [`matchAll();`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#regexp.exec_et_matchall), mais les fois que je l'ai testé elle ne marchait pas bien.

Veux-tu que je prenne le temps de regarder ça ?

2023-02-28 13:54 UTC, forestmaxime approved these changes

2023-02-28 13:55 UTC, forestmaxime commented on utils/algolia.js
> +        for (;;) {
C'est good. Je te l'approuve tel quel.

2023-02-28 14:08 UTC, merged